name: Bump Version
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
jobs:
  bump-version:
    name: Bump Version on master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:  
          token: ${{ secrets.ACTION_GITHUB_TOKEN }}

      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        with:
          minor-wording: 'feat, perf'
          major-wording: 'build, major'
          skip-tag: false
          default: patch
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}

      - name: Output Step
        env:
          NEW_TAG: '${{ steps.version-bump.outputs.newTag }}'
        run: echo "new tag $NEW_TAG"
