name: Bump Version
'on':
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
jobs:
  bump-version:
    name: Bump Version on master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        with:  
          token: ${{ secrets.ACTION_GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        with:
          minor-wording: 'feat, perf'
          major-wording: 'build, major'
          skip-tag: false
          default: patch
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Output Step
        env:
          NEW_TAG: '${{ steps.version-bump.outputs.newTag }}'
        run: echo "new tag $NEW_TAG"
